name: Dissect CI
on: [push, pull_request, workflow_dispatch]

jobs: 
  ci:
    uses: fox-it/dissect-workflow-templates/.github/workflows/dissect-ci-template.yml@main
    with:
      on-demand-test: 'dissect.target'
    secrets: inherit
